version: "3"
services:
  chromedriver:
    image: selenium/standalone-chrome

  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_DB=QuotesScraper
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment: 
      - PGADMIN_DEFAULT_EMAIL=123@abc.com
      - PGADMIN_DEFAULT_PASSWORD=userpass
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
      - PGADMIN_LISTEN_PORT=80
    ports: 
      - "88:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin4
    logging:
      driver: "none"

  api:
    build: . 
    depends_on:
      - chromedriver
      - postgres
    restart: on-failure
    ports:
      - "3000:3000"
    command: "uvicorn api.main:app --host 0.0.0.0 --port 3000"

